INSERT INTO MOVIES (TITLE,RUNTIME,GENRE,IMDB_SCORE,RATING)
VALUES ('Howard the Duck','110','Sci-Fi','4.6','PG');

INSERT INTO MOVIES (TITLE,RUNTIME,GENRE,IMDB_SCORE,RATING)
VALUES ('Lavalantula','83','Horror','4.7','TV-14');

INSERT INTO MOVIES (TITLE,RUNTIME,GENRE,IMDB_SCORE,RATING)
VALUES ('Starship Troopers','129','Sci-Fi','7.2','PG-13');

INSERT INTO MOVIES (TITLE,RUNTIME,GENRE,IMDB_SCORE,RATING)
VALUES ('Waltz With Bashir','90','Documentary','8.0','R');

INSERT INTO MOVIES (TITLE,RUNTIME,GENRE,IMDB_SCORE,RATING)
VALUES ('Spaceballs','96','Comedy','7.1','PG');

INSERT INTO MOVIES (TITLE,RUNTIME,GENRE,IMDB_SCORE,RATING)
VALUES ('Monsters Inc.','92','Animation','8.1','G');

SELECT TITLE FROM MOVIES
WHERE GENRE = 'Sci-Fi';


SELECT TITLE, RUNTIME, RATING FROM MOVIES
WHERE RATING = 'PG' OR RATING = 'G'
AND RUNTIME <= '100';

SELECT GENRE, AVG(IMDB_SCORE) FROM MOVIES
GROUP BY
GENRE

UPDATE MOVIES SET RATING = 'R'
WHERE TITLE = 'Starship Troopers';

SELECT ID,RATING FROM MOVIES
WHERE GENRE = 'Horror' OR GENRE = 'Documentary';

SELECT  GENRE,AVG(IMDB_SCORE), MAX(IMDB_SCORE),MIN(IMDB_SCORE) FROM MOVIES
GROUP BY GENRE
HAVING COUNT(*) > 1;

DELETE FROM MOVIES WHERE RATING = 'R';




